### ISSUE TITLE
$orderSort is undefined in CustomerOrders resolver class

### ISSUE THREAD

**Issue by WillSs-Dev** [scandipwa/sales-graphql#19]
When trying to fetch orders from a client in ScandiPwa I received this error message from the query result:

```
"errors": [
        {
            "message": "Internal server error",
            "extensions": {
                "debugMessage": "Warning: Undefined variable $orderSort in \/home\/willian\/Projects\/project\/vendor\/scandipwa\/sales-graphql\/Model\/Resolver\/CustomerOrders.php on line 83",
```

                
Taking a look at the CustomerOrders class inside the module and the CoreCustomerOrders which it extends from, I noticed that in the 
`__construct` method `$orderSort` is supposed to be passed to the parent class but it is not being received as a parameter:

```
public function __construct(
        OrderRepositoryInterface $orderRepository,
        SearchCriteriaBuilder $searchCriteriaBuilder,
        OrderFilter $orderFilter,
        OrderFormatter $orderFormatter,
        SortOrderBuilder $sortOrderBuilder,   <--
        ?StoreManagerInterface   $storeManager = null
    ) {
```

Instead, the resolver is receiving `$sortOrderBuilder` which is not being used anywhere in the code. I replaced `$sortOrderBuilder` for `$orderSort` and the query now returns the expected data to the FE:

```
public function __construct(
        OrderRepositoryInterface $orderRepository,
        SearchCriteriaBuilder $searchCriteriaBuilder,
        OrderFilter $orderFilter,
        OrderFormatter $orderFormatter,
        OrderSort $orderSort,  <--
        ?StoreManagerInterface   $storeManager = null
    ) {
```

**Comment by tommoholmes** [comment]
I got error too

**Comment by AleksandrsKondratjevs** [comment]
Fixed in https://github.com/scandipwa/sales-graphql/commit/1209c9db7fc16894e591debf91e6b0343d96f3e3
